### ISSUE TITLE
Library needs to be updated. Requests- Toolsbelt was updated today and  Pyrebase4 now throws import error

### ISSUE THREAD

**Issue by emma125dgggd** [nhorvath/Pyrebase4#62]
File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/app/cleeve-2/main.py", line 35, in <module>
    import pyrebase
File "/home/appuser/venv/lib/python3.9/site-packages/pyrebase/__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
File "/home/appuser/venv/lib/python3.9/site-packages/pyrebase/pyrebase.py", line 20, in <module>
    from requests_toolbelt.adapters import appengine
File "/home/appuser/venv/lib/python3.9/site-packages/requests_toolbelt/adapters/appengine.py", line 42, in <module>
    from .._compat import gaecontrib

**Comment by GitMarco27** [comment]
Downgrading **requests-toolbelt** to the previous version fixes the problem for the moment:

`pip install requests-toolbelt==0.10.1`

**Comment by eric-truss** [comment]
To add onto this, looks like Requests was also updated today to add support for `urllib3 2.0` and has some "minor breaking changes": https://github.com/psf/requests/releases/tag/v2.30.0

In order to fix that, pin to the previous version of requests: `requests==2.29.0`

**Comment by Moinshaikh2602** [comment]
> To add onto this, looks like Requests was also updated today to add support for `urllib3 2.0` and has some "minor breaking changes": https://github.com/psf/requests/releases/tag/v2.30.0
> 
> In order to fix that, pin to the previous version of requests: `requests==2.29.0`

Thank you , I was getting same issue

**Comment by emma125dgggd** [comment]
> To add onto this, looks like Requests was also updated today to add support for `urllib3 2.0` and has some "minor breaking changes": https://github.com/psf/requests/releases/tag/v2.30.0
> 
> In order to fix that, pin to the previous version of requests: `requests==2.29.0`

doesn't work at my end
File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script

    exec(code, module.__dict__)

  File "main.py", line 35, in <module>

    import pyrebase

  File "/home/appuser/venv/lib/python3.9/site-packages/pyrebase/__init__.py", line 1, in <module>

    from .pyrebase import initialize_app

  File "/home/appuser/venv/lib/python3.9/site-packages/pyrebase/pyrebase.py", line 19, in <module>

    from requests.packages.urllib3.contrib.appengine import is_appengine_sandbox

ModuleNotFoundError: No module named 'requests.packages.urllib3.contrib.appengine'

Database

**Comment by MasterPhoton** [comment]
facing the same issue

**Comment by Moinshaikh2602** [comment]
> facing the same issue

Add these dependencies in requirements.txt

```
requests-toolbelt==0.10.1 
requests==2.29.0 
urllib3 
```

**Comment by anupamkayal** [comment]
> > facing the same issue
> 
> Add these dependencies in requirements.txt
> 
> ```
> requests-toolbelt==0.10.1 
> requests==2.29.0 
> urllib3 
> ```

Yes you are right, but if the problem exists then install this library separately such as 
```
pip install requests==2.29.0
```

**Comment by nhorvath** [comment]
fixed in v4.7.0

**Comment by Moinshaikh2602** [comment]
> fixed in v4.7.0

Still getting this error after updating version

`InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load : cannot import name 'gaecontrib' from 'requests_toolbelt._compat' (/usr/local/lib/python3.9/site-packages/requests_toolbelt/_compat.py)`

when i freeze the versions of other packages it will worked

```
requests-toolbelt==0.10.1
requests==2.29.0
urllib3
```

**Comment by nhorvath-bowery** [comment]
That is exactly what is in requirements.txt now (even though it's bad practice and should be changed)

**Comment by boyintheroom** [comment]
> That is exactly what is in requirements.txt now (even though it's bad practice and should be changed)

hi. what is the purpose of requirements.txt? im new.
also i have kivmob master. it installs latest version of requests and requests_toolbelt everytime i build my kivy app. i have defined the versions in buildozer.spec also but still shows the error of *ModuleNotFoundError: No module named 'requests.packages.urllib3.contrib.appengine'*

**Comment by AsifArmanRahman** [comment]
> what is the purpose of requirements.txt?

The requirements.txt file is used for specifying what python packages are required to run the project. It stores the information of what packages with specified versions are needed for running the project.

> it installs latest version of requests and requests_toolbelt everytime

The latest version of these library has a breaking change, and that change is causing the error you're facing.

**Comment by AsifArmanRahman** [comment]
Based on the deps of the libraries you're using to build your app; it could be because of that. Find a suitable version of libraries which work with the exact version of the 3 mentioned libraries in your original question.

**Comment by AlejandroPG10** [comment]
I'm trying to compile my apk and apk crashes on android. 
I already know that this is related to the problem you're talking about. I was using pyrebase 4.6.0. 
Can anybody tell me what I have to specified on my buildozer.spec (requirements)? 
Which versions of these libraries I have to use?

I tried with the version of the packs you wrote on this post but does not work for me.

Thank you in advance.

**Comment by Moinshaikh2602** [comment]
> I'm trying to compile my apk and apk crashes on android. 
> I already know that this is related to the problem you're talking about. I was using pyrebase 4.6.0. 
> Can anybody tell me what I have to specified on my buildozer.spec (requirements)? 
> Which versions of these libraries I have to use?
> 
> I tried with the version of the packs you wrote on this post but does not work for me.
> 
> Thank you in advance.

```
requests-toolbelt==0.10.1
requests==2.29.0
urllib3
```

**Comment by AlejandroPG10** [comment]
> > I'm trying to compile my apk and apk crashes on android.
> > I already know that this is related to the problem you're talking about. I was using pyrebase 4.6.0.
> > Can anybody tell me what I have to specified on my buildozer.spec (requirements)?
> > Which versions of these libraries I have to use?
> > I tried with the version of the packs you wrote on this post but does not work for me.
> > Thank you in advance.
> 
> ```
> requests-toolbelt==0.10.1
> requests==2.29.0
> urllib3
> ```

I tried like this with pyrebase 4.6.0. It is necessary to use 4.7.0?
I've read some comments about it but I don't know if by installing the new version I'm going to solve it

**Comment by Moinshaikh2602** [comment]
> > > I'm trying to compile my apk and apk crashes on android.
> > > I already know that this is related to the problem you're talking about. I was using pyrebase 4.6.0.
> > > Can anybody tell me what I have to specified on my buildozer.spec (requirements)?
> > > Which versions of these libraries I have to use?
> > > I tried with the version of the packs you wrote on this post but does not work for me.
> > > Thank you in advance.
> > 
> > ```
> > requests-toolbelt==0.10.1
> > requests==2.29.0
> > urllib3
> > ```
> 
> I tried like this with pyrebase 4.6.0. It is necessary to use 4.7.0?
> I've read some comments about it but I don't know if by installing the new version I'm going to solve it
> 

No , for now you have to install these 3 packages with pyrebase 4.6.0 and 4.7.0

You can read some comments above for more details

**Comment by kwkbtr** [comment]
Changing versions in `requirements.txt` doesn't affect user installation.
`install_requires` in `setup.py` should be updated to fix user installation.

**Comment by nhorvath** [comment]
Thanks... I can't belive I missed that. Will fix today.

**Comment by nhorvath** [comment]
Fixed requirements in https://pypi.org/manage/project/Pyrebase4/release/4.7.1/ thanks for the help.
